import {
  speak,
  indicateLocation,
  indicateSuccess,
  addCharacter,
  removeCharacter,
} from '../game/gameActions';

export default {
  name: '3 Little Piggies',
  solution: [
    speak('Once upon a time there was a mother pig that had three little piggies. Mother pig wore white and the three little piggies wore red, blue and yellow. They all lived at mother pig’s white house. Put mother pig and the three little piggies at mother pig’s house.'),
    indicateLocation(0),
    addCharacter(8, 0),
    addCharacter(9, 0),
    addCharacter(10, 0),
    addCharacter(11, 0),
    indicateSuccess(0),
    speak('Near mother pig’s house there was a green forest. In the green forest lived a wolf. The wolf wore black. Put the wolf in the forest.'),
    indicateLocation(4),
    addCharacter(12, 4),
    indicateSuccess(4),
    speak(`Mother pig did not have enough food and told the little piggies: ‘Go out and seek your fortune, but beware the big bad wolf.’ The piggies went out in the world.
The first little piggy was wearing yellow. He was lazy and he built his house out of yellow straw. Now the first little piggy lives in the yellow straw house.`),
    indicateLocation(1),
    removeCharacter(9, 0),
    indicateSuccess(0),
    addCharacter(9, 1),
    indicateSuccess(1),
    speak('The second little piggy always wore blue. He was also lazy and he built his house out of brown twigs. Now the second little piggie lives in the brown twig house.'),
    indicateLocation(2),
    removeCharacter(10, 0),
    indicateSuccess(0),
    addCharacter(10, 2),
    indicateSuccess(2),
    speak('The third little piggy was wearing red. He was not lazy and he built his house out of red brick. Now the third little piggy lives in the red brick house.'),
    indicateLocation(3),
    removeCharacter(11, 0),
    indicateSuccess(0),
    addCharacter(11, 3),
    indicateSuccess(3),
    speak('The next day, a wolf passed by and he smelled the little piggies and wanted to eat them. He first went from the forest to the first piggy’s house.'),
    indicateLocation(4),
    removeCharacter(12, 4),
    indicateSuccess(12),
    indicateLocation(1),
    addCharacter(12, 1),
    indicateSuccess(1),
    speak(`So he knocked on the door and said:  "Little pig! Little pig! Let me in! Let me in!"
But the little pig saw the wolf's big paws through the keyhole, so he answered back:
 "No! No! No! Not by the hairs on my chinny chin chin!" Then the wolf showed his teeth and said: "Then I'll huff and I'll puff and I'll blow your house down." So he huffed and he puffed and he blew the house down! The wolf opened his jaws very wide and bit down as hard as he could, but the first little pig escaped and ran away to hide with the second little pig. Move the first little piggy to the brown twig house.`),
    indicateLocation(1),
    removeCharacter(2, 1),
    indicateSuccess(1),
    indicateLocation(2),
    addCharacter(9, 2),
    indicateSuccess(2),
    speak('Then the wolf went to the second little piggy’s house, the brown twig house'),
    indicateLocation(1),
    removeCharacter(12, 1),
    indicateSuccess(1),
    indicateLocation(2),
    addCharacter(12, 2),
    indicateSuccess(2),
    speak(`So he knocked on the door and said:  "Little pig! Little pig! Let me in! Let me in!"
But the little pig saw the wolf's big paws through the keyhole, so he answered back:
 "No! No! No! Not by the hairs on my chinny chin chin!" Then the wolf showed his teeth and said: "Then I'll huff and I'll puff and I'll blow your house down." So he huffed and he puffed and he blew the house down! The wolf opened his jaws very wide and bit down as hard as he could, but the first and second little pigs escaped and ran away to hide with the third little pig.  Move first and second little piggy to the red brick house.`),
    indicateLocation(2),
    removeCharacter(9, 2),
    indicateLocation(3),
    addCharacter(9, 3),
    indicateLocation(2),
    removeCharacter(10, 2),
    indicateLocation(3),
    addCharacter(10, 3),
    indicateSuccess(2),
    indicateSuccess(3),
    speak('Then the wolf went to the third little piggy’s house, the red brick house'),
    indicateLocation(2),
    removeCharacter(12, 2),
    indicateLocation(3),
    addCharacter(12, 3),
    indicateSuccess(2),
    indicateSuccess(3),
    speak(`So he knocked on the door and said:  "Little pig! Little pig! Let me in! Let me in!"
But the little pig saw the wolf's big paws through the keyhole, so he answered back:
 "No! No! No! Not by the hairs on my chinny chin chin!" Then the wolf showed his teeth and said: "Then I'll huff and I'll puff and I'll blow your house down." Well! he huffed and he puffed.

He puffed and he huffed. And he huffed, huffed, and he puffed, puffed; but he could not blow the house down. So the little piggies lived happily ever after and the wolf returned to the green forest`),
    indicateLocation(3),
    removeCharacter(12, 3),
    indicateLocation(4),
    addCharacter(12, 4),
    indicateSuccess(3),
    indicateSuccess(4),
    speak('The end!')
  ]
};
